language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

env:
  - SYMFONY_VERSION=2.6.*

before_script:
    - composer self-update || true
    - composer install --dev --prefer-source

script:
  - bin/atoum

notifications:
    email:
        recipients:
            - thomas@scullwm.com
        on_success: change
        on_failure: change
